SHELL=/bin/sh #Shell da utilizzare per l'esecuzione dei comandi

all:
	g++ -DEVAL -static -O2 -std=c++11 -o pokemon pokemon.cpp
clean:
	rm -f pokemon pokemon.
test:
	sh ./test.sh
test1:
	bash ./test.sh
mac:
	g++ -DEVAL -O2 -std=c++11 -o pokemon pokemon.cpp
